import streamlit as st
st.write()
st.title("BMI Calculator")
st.write("#### A BMI (Body Mass Index) Calculator is a tool used to determine whether a person has a healthy weight based on their height and weight")
h = st.slider("Enter Your Height (in CM) :",min_value=50,max_value=300,value=175)
w = st.slider("Enter Your Weight (in KG) :",max_value=635,value=50)
# BMI formula Bmi = weight/height**2
bmi = w / ((h//100)**2)
st.write(f"Your BMi is {bmi:.2f}")
st.markdown("## BMI Catagories")
st.write("- Underweight: BMI < 18.5")
st.write("- Normal weight: 18.5 ≤ BMI < 24.9")
st.write("- Overweight: 25 ≤ BMI < 29.9")
st.write("- Obese: BMI ≥ 30")
st.write("Made by *Munna RDX* :sunglasses:")
